export const assets = [
    {url: "./suelo.png", name:"Suelo"},
    {url: "./cielo.png", name:"Cielo"},
    {url: "./burbuja.png", name:"Dialogo"},
    {url: "uipack-space/PNG/metalPanel_blueCorner.png", name:"PanelBlue"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/wrench.png", name:"Config"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/save.png", name:"Save"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/musicOff.png", name:"MusicOff"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/musicOn.png", name:"MusicOn"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/Black/2x/buttonStart.png", name:"Start"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/buttonStart.png", name:"StartW"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/Black/2x/cross.png", name:"Cross"},
    {url: "./spritesheet.json", name:"MaxMov"},
    {url: "./spritesheet (1).json", name:"Juan"},
    {url: "./uipack-rpg/Spritesheet/uipack_rpg_sheet", name:"RPSheet"},
    {url: "./uipack-rpg/PNG/cursorGauntlet_grey.png", name:"Guante"},
    {url: "./uipack_fixed/PNG/blue_boxCross.png", name:"XAzul"},
    {url: "./StartScene/Juan y El Dragon.png", name:"BG"},
    {url: "./StartScene/START.png", name:"Start1"},
    {url: "./StartScene/START (1).png", name:"Start2"},
    {url: "./StartScene/START (2).png", name:"Start3"},
    {url: "./StageOne/BG.png", name:"SceneBG"},
    {url: "./StageOne/Floor2.png", name:"Floor"},
    {url: "./uipack-space/Spritesheet/uipackSpace_sheet.xml", name:"SpaceUI"},
    {url: "./StageOne/Dragon/DrgAtk1.png", name:"DrgAtk1"},
    {url: "./StageOne/Dragon/DrgFire1.png", name:"DrgFire1"},
    {url: "./StageOne/Potion.png", name:"Potion"},
]