export const assets = [
    {url: "./MAXIM2.png", name:"Maxim"},
    {url: "./suelo.png", name:"Suelo"},
    {url: "./cielo.png", name:"Cielo"},
    {url: "./MAXIMTRANSPARENTE1.png", name:"MaximRun1"},
    {url: "./MAXIMTRANSPARENTE2.png", name:"MaximRun2"},
    {url: "./burbuja.png", name:"Dialogo"},
    {url: "uipack-space/PNG/metalPanel_blueCorner.png", name:"PanelBlue"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/wrench.png", name:"Config"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/save.png", name:"Save"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/musicOff.png", name:"MusicOff"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/musicOn.png", name:"MusicOn"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/Black/2x/buttonStart.png", name:"Start"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/White/2x/buttonStart.png", name:"StartW"},
    {url: "gameicons-expansion/Game-icons-(base)/PNG/Black/2x/cross.png", name:"Cross"},
    {url: "./spritesheet.json", name:"MaxMov"},
    {url: "./spritesheet (1).json", name:"Juan"},
    {url: "./uipack-rpg/PNG/cursorGauntlet_grey.png", name:"Guante"},
    {url: "./uipack_fixed/PNG/blue_boxCross.png", name:"XAzul"},
    {url: "maps/casita.json", name:"Casa"},
    {url: "Juan y El Dragon.png", name:"BG"},
]